image: docker:latest

pipelines:
  services:
    - mysql:latest

  stages:
    - build

  .build:
    image: maven:3-jdk-17
    stage: build
    when: manual
    script: "mvn clean install -DskipTests"
    artifacts:
      paths:
        - target/*.jar
    only:
      - master
