image: maven:3-jdk-17

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - mvn clean install -DskipTests=true --file pom.xml
            after-script:
              - pipe: atlassian/checkstyle-report:0.3.0
        - step:
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.5.1