#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.
options:
  docker: true

image: docker:latest
pipelines:
  custom: # defines that this can only be triggered manually or by a schedule
    build:
      - step:
          image: maven:3.8.3-openjdk-17
          name: Build
          script:
            - mvn clean install -DskipTests=true package spring-boot:repackage
          artifacts:
            paths:
              - target/*.jar
